version: '3'

services:
  api:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/run
    environment:
     - DJANGO_SETTINGS_MODULE=backend.settings
  
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.data
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p
      interval: 1s
      retries: 10
      start_period: 3s
      timeout: 20s
    volumes:
        - ./mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ./mysql/db.env